#!/usr/bin/env python3
"""Merges data/probes-*.json into test-features-matrix.json + MATRIX.md.

Per probe and product it derives the first swept version that supports the
feature, and flags gaps (supported, then unsupported again) so that a simple
`>=x.y.z` constraint is only emitted when it is actually truthful.
"""
import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# probe -> (feature label, note)
FEATURES = {
    "01-basic-json": ("`.tftest.json` test file", "JSON syntax, plan run, assert on a known value"),
    "02-basic-hcl": ("`.tftest.hcl` test file", "control"),
    "03-expect-failures-variable": ("`expect_failures` → variable `validation`", ""),
    "04-expect-failures-output": ("`expect_failures` → output `precondition`", ""),
    "05-expect-failures-check": ("`expect_failures` → `check` block", ""),
    "06-mock-provider-apply": ("`mock_provider` + `mock_resource.defaults` (apply)", ""),
    "07-override-resource": ("`override_resource` (JSON syntax)", ""),
    "08-mock-known-at-plan": ("mock values known at plan *without* `override_during`", "informational: pass = mocks materialise during plan by default"),
    "09-override-during-plan-mock": ("`override_during = plan` on `mock_provider`", ""),
    "10-override-during-plan-override": ("`override_during = plan` on `override_resource`", ""),
    "11-state-key": ("`run.state_key`", ""),
    "12-parallel-runs": ("`test { parallel }` + `run.parallel`", "also needs `state_key`"),
    "13-test-file-variable-block": ("`variable` block inside test file", ""),
    "14-file-variables-ref-run-output": ("file-level `variables` referencing `run.<name>`", ""),
    "15-run-variables-ref-run-output": ("run-level `variables` referencing `run.<name>`", ""),
    "16-mock-source-file": ("`mock_provider.source` + `.tfmock.json`", ""),
    "17-mock-functions": ("functions inside mock `defaults`", ""),
    "18-skip-cleanup": ("`run.skip_cleanup`", "experimental builds only on Terraform"),
    "19-junit-xml": ("`-junit-xml` flag", ""),
    "20-tofutest-extension": ("`.tofutest.json` extension", "OpenTofu-only by design"),
    "21-helper-module": ("`run.module { source }` helper module + `run.<name>` output", ""),
    "22-override-remote-state": ("`override_data` on `terraform_remote_state` (CDKTN cross-stack shape, with backend block)", ""),
    "23-assert-ref-run-output": ("`assert.condition` referencing `run.<name>.<output>`", ""),
    "24-run-variables-ref-file-variables": ("run `variables` referencing a file-level `variables` entry", "opentofu/opentofu#4567"),
    "25-tofutest-shadowing": ("`.tofutest.json` shadows same-basename `.tftest.json` unparsed", "the dual-engine escape hatch; OpenTofu-only by design"),
    "26-failing-check-fails-run": ("failing `check` block (a plan/apply *warning*) fails the test run", "behavioural: pass = run status is `fail` or `error`"),
}


def vkey(v):
    return tuple(int(x) for x in v.split("."))


digests = [json.load(open(f)) for f in glob.glob(os.path.join(ROOT, "data", "probes-*.json"))]
products = {}
for d in digests:
    products.setdefault(d["product"], {})[d["version"]] = d["probes"]

matrix = {"products": {p: sorted(vs, key=vkey) for p, vs in products.items()}, "features": {}}
for probe, (label, note) in FEATURES.items():
    entry = {"label": label, "note": note, "products": {}}
    for product, versions in products.items():
        ordered = sorted(versions, key=vkey)
        supported = [v for v in ordered if versions[v].get(probe, {}).get("supported")]
        since = supported[0] if supported else None
        gaps = [v for v in ordered if since and vkey(v) > vkey(since) and v not in supported]
        last_error = None
        if not supported or gaps:
            failing = [v for v in ordered if v not in supported]
            last_error = versions[failing[-1]].get(probe, {}).get("error")
        entry["products"][product] = {"since": since, "supported": supported, "gaps": gaps,
                                      "latest_error": last_error}
    matrix["features"][probe] = entry

with open(os.path.join(ROOT, "test-features-matrix.json"), "w") as f:
    json.dump(matrix, f, indent=2)
    f.write("\n")

order = [p for p in ("terraform", "opentofu") if p in products]
lines = ["# `terraform test` / `tofu test` feature matrix", "",
         "Generated by `scripts/build-matrix.py` from `data/probes-*.json` — do not edit.", "",
         "Swept versions:", ""]
for p in order:
    lines.append(f"- **{p}**: {', '.join(matrix['products'][p])}")
lines += ["", "First swept version in which each probe passes (— = never; ⚠ = regressed in listed versions):", "",
          "| Probe | Feature | " + " | ".join(order) + " |", "| --- | --- | " + " | ".join("---" for _ in order) + " |"]
for probe, entry in matrix["features"].items():
    cells = []
    for p in order:
        info = entry["products"][p]
        cell = f"≥ {info['since']}" if info["since"] else "—"
        if info["gaps"]:
            cell += f" ⚠ {', '.join(info['gaps'])}"
        cells.append(cell)
    label = entry["label"] + (f" ({entry['note']})" if entry["note"] else "")
    lines.append(f"| {probe[:2]} | {label} | " + " | ".join(cells) + " |")
lines += ["", "## Failure messages (latest failing version)", ""]
for probe, entry in matrix["features"].items():
    for p in order:
        err = entry["products"][p]["latest_error"]
        if err:
            err = re.sub(r"\x1b\[[0-9;]*m|[│╷╵]", "", err)
            err = err[err.rfind("Error:"):] if "Error:" in err else err  # skip init's boilerplate preamble
            lines.append(f"- **{probe} / {p}**: `{' '.join(err.split())[:300]}`")
with open(os.path.join(ROOT, "MATRIX.md"), "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"{len(digests)} digests -> test-features-matrix.json, MATRIX.md")
